load("//core:builddefs.bzl", "COPTS", "DEFINES")

cc_library(
    name = "camera",
    srcs = ["camera.cc"],
    hdrs = ["camera.h"],
    copts = COPTS,
    defines = DEFINES,
    visibility = ["//visibility:public"],
    deps = [
        "@glm",
    ],
)
